name: autopkgtest-results-formatter
version: '0.1'
summary: Format autopkgtest results
description: |
  Download autopkgtest results from the Ubuntu index and print them to a
  markdown file.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  autopkgtest-results-formatter:
    command: autopkgtest_results_formatter
    plugs: [network, home]

parts:
  autopkgtest-results-formatter:
    source: .
    plugin: python
